//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:50:40 PM CST 
//


package com.danju.xml.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="styleClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="djbs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="djbslx" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="djbhq" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="djcx" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="djdymc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="operation" maxOccurs="100">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute ref="{}name use="required""/>
 *                           &lt;attribute ref="{}cname use="required""/>
 *                           &lt;attribute ref="{}key"/>
 *                           &lt;attribute ref="{}disable"/>
 *                           &lt;attribute ref="{}type"/>
 *                           &lt;attribute ref="{}ac"/>
 *                           &lt;attribute ref="{}djxg"/>
 *                           &lt;attribute ref="{}retval"/>
 *                           &lt;attribute ref="{}djlock"/>
 *                           &lt;attribute ref="{}other"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="masterinfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="mcol" maxOccurs="200">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute ref="{}name use="required""/>
 *                           &lt;attribute ref="{}cname use="required""/>
 *                           &lt;attribute ref="{}type"/>
 *                           &lt;attribute ref="{}singleline"/>
 *                           &lt;attribute ref="{}size"/>
 *                           &lt;attribute ref="{}required"/>
 *                           &lt;attribute ref="{}format"/>
 *                           &lt;attribute ref="{}default"/>
 *                           &lt;attribute ref="{}readonly"/>
 *                           &lt;attribute ref="{}modify"/>
 *                           &lt;attribute ref="{}dqname"/>
 *                           &lt;attribute ref="{}retval"/>
 *                           &lt;attribute ref="{}xycol"/>
 *                           &lt;attribute ref="{}value"/>
 *                           &lt;attribute ref="{}other"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute ref="{}tablename use="required""/>
 *                 &lt;attribute ref="{}bchz"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="detailinfos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="detailinfo" maxOccurs="20">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="submit_addjs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="submit_modjs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="dcol" maxOccurs="200">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute ref="{}name use="required""/>
 *                                     &lt;attribute ref="{}cname use="required""/>
 *                                     &lt;attribute ref="{}type"/>
 *                                     &lt;attribute ref="{}singleline"/>
 *                                     &lt;attribute ref="{}size"/>
 *                                     &lt;attribute ref="{}required"/>
 *                                     &lt;attribute ref="{}format"/>
 *                                     &lt;attribute ref="{}default"/>
 *                                     &lt;attribute ref="{}readonly"/>
 *                                     &lt;attribute ref="{}modify"/>
 *                                     &lt;attribute ref="{}dqname"/>
 *                                     &lt;attribute ref="{}retval"/>
 *                                     &lt;attribute ref="{}xycol"/>
 *                                     &lt;attribute ref="{}value"/>
 *                                     &lt;attribute ref="{}other"/>
 *                                     &lt;attribute ref="{}align"/>
 *                                     &lt;attribute ref="{}onblur"/>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="dfoot" maxOccurs="10">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute ref="{}name use="required""/>
 *                                     &lt;attribute ref="{}cname use="required""/>
 *                                     &lt;attribute ref="{}type"/>
 *                                     &lt;attribute ref="{}singleline"/>
 *                                     &lt;attribute ref="{}size"/>
 *                                     &lt;attribute ref="{}required"/>
 *                                     &lt;attribute ref="{}format"/>
 *                                     &lt;attribute ref="{}default"/>
 *                                     &lt;attribute ref="{}readonly"/>
 *                                     &lt;attribute ref="{}modify"/>
 *                                     &lt;attribute ref="{}dqname"/>
 *                                     &lt;attribute ref="{}retval"/>
 *                                     &lt;attribute ref="{}xycol"/>
 *                                     &lt;attribute ref="{}value"/>
 *                                     &lt;attribute ref="{}other"/>
 *                                     &lt;attribute ref="{}align"/>
 *                                     &lt;attribute ref="{}onblur"/>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute ref="{}name use="required""/>
 *                           &lt;attribute ref="{}cname use="required""/>
 *                           &lt;attribute ref="{}tablename use="required""/>
 *                           &lt;attribute ref="{}pagesize use="required""/>
 *                           &lt;attribute ref="{}colname use="required""/>
 *                           &lt;attribute ref="{}mxcc"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "cname",
    "styleClass",
    "djbs",
    "djbslx",
    "djbhq",
    "djcx",
    "djdymc",
    "operations",
    "masterinfo",
    "detailinfos"
})
@XmlRootElement(name = "dj")
public class Dj {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String cname;
    @XmlElement(required = true)
    protected String styleClass;
    @XmlElement(required = true)
    protected String djbs;
    @XmlElement(required = true)
    protected String djbslx;
    @XmlElement(required = true)
    protected String djbhq;
    @XmlElement(required = true)
    protected String djcx;
    @XmlElement(required = true)
    protected String djdymc;
    @XmlElement(required = true)
    protected Dj.Operations operations;
    @XmlElement(required = true)
    protected Dj.Masterinfo masterinfo;
    @XmlElement(required = true)
    protected Dj.Detailinfos detailinfos;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the cname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCname() {
        return cname;
    }

    /**
     * Sets the value of the cname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCname(String value) {
        this.cname = value;
    }

    /**
     * Gets the value of the styleClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyleClass() {
        return styleClass;
    }

    /**
     * Sets the value of the styleClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyleClass(String value) {
        this.styleClass = value;
    }

    /**
     * Gets the value of the djbs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjbs() {
        return djbs;
    }

    /**
     * Sets the value of the djbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjbs(String value) {
        this.djbs = value;
    }

    /**
     * Gets the value of the djbslx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjbslx() {
        return djbslx;
    }

    /**
     * Sets the value of the djbslx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjbslx(String value) {
        this.djbslx = value;
    }

    /**
     * Gets the value of the djbhq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjbhq() {
        return djbhq;
    }

    /**
     * Sets the value of the djbhq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjbhq(String value) {
        this.djbhq = value;
    }

    /**
     * Gets the value of the djcx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjcx() {
        return djcx;
    }

    /**
     * Sets the value of the djcx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjcx(String value) {
        this.djcx = value;
    }

    /**
     * Gets the value of the djdymc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjdymc() {
        return djdymc;
    }

    /**
     * Sets the value of the djdymc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjdymc(String value) {
        this.djdymc = value;
    }

    /**
     * Gets the value of the operations property.
     * 
     * @return
     *     possible object is
     *     {@link Dj.Operations }
     *     
     */
    public Dj.Operations getOperations() {
        return operations;
    }

    /**
     * Sets the value of the operations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dj.Operations }
     *     
     */
    public void setOperations(Dj.Operations value) {
        this.operations = value;
    }

    /**
     * Gets the value of the masterinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Dj.Masterinfo }
     *     
     */
    public Dj.Masterinfo getMasterinfo() {
        return masterinfo;
    }

    /**
     * Sets the value of the masterinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dj.Masterinfo }
     *     
     */
    public void setMasterinfo(Dj.Masterinfo value) {
        this.masterinfo = value;
    }

    /**
     * Gets the value of the detailinfos property.
     * 
     * @return
     *     possible object is
     *     {@link Dj.Detailinfos }
     *     
     */
    public Dj.Detailinfos getDetailinfos() {
        return detailinfos;
    }

    /**
     * Sets the value of the detailinfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dj.Detailinfos }
     *     
     */
    public void setDetailinfos(Dj.Detailinfos value) {
        this.detailinfos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="detailinfo" maxOccurs="20">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="submit_addjs" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="submit_modjs" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="dcol" maxOccurs="200">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute ref="{}name use="required""/>
     *                           &lt;attribute ref="{}cname use="required""/>
     *                           &lt;attribute ref="{}type"/>
     *                           &lt;attribute ref="{}singleline"/>
     *                           &lt;attribute ref="{}size"/>
     *                           &lt;attribute ref="{}required"/>
     *                           &lt;attribute ref="{}format"/>
     *                           &lt;attribute ref="{}default"/>
     *                           &lt;attribute ref="{}readonly"/>
     *                           &lt;attribute ref="{}modify"/>
     *                           &lt;attribute ref="{}dqname"/>
     *                           &lt;attribute ref="{}retval"/>
     *                           &lt;attribute ref="{}xycol"/>
     *                           &lt;attribute ref="{}value"/>
     *                           &lt;attribute ref="{}other"/>
     *                           &lt;attribute ref="{}align"/>
     *                           &lt;attribute ref="{}onblur"/>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="dfoot" maxOccurs="10">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute ref="{}name use="required""/>
     *                           &lt;attribute ref="{}cname use="required""/>
     *                           &lt;attribute ref="{}type"/>
     *                           &lt;attribute ref="{}singleline"/>
     *                           &lt;attribute ref="{}size"/>
     *                           &lt;attribute ref="{}required"/>
     *                           &lt;attribute ref="{}format"/>
     *                           &lt;attribute ref="{}default"/>
     *                           &lt;attribute ref="{}readonly"/>
     *                           &lt;attribute ref="{}modify"/>
     *                           &lt;attribute ref="{}dqname"/>
     *                           &lt;attribute ref="{}retval"/>
     *                           &lt;attribute ref="{}xycol"/>
     *                           &lt;attribute ref="{}value"/>
     *                           &lt;attribute ref="{}other"/>
     *                           &lt;attribute ref="{}align"/>
     *                           &lt;attribute ref="{}onblur"/>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute ref="{}name use="required""/>
     *                 &lt;attribute ref="{}cname use="required""/>
     *                 &lt;attribute ref="{}tablename use="required""/>
     *                 &lt;attribute ref="{}pagesize use="required""/>
     *                 &lt;attribute ref="{}colname use="required""/>
     *                 &lt;attribute ref="{}mxcc"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "detailinfo"
    })
    public static class Detailinfos {

        @XmlElement(required = true)
        protected List<Dj.Detailinfos.Detailinfo> detailinfo;

        /**
         * Gets the value of the detailinfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the detailinfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDetailinfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dj.Detailinfos.Detailinfo }
         * 
         * 
         */
        public List<Dj.Detailinfos.Detailinfo> getDetailinfo() {
            if (detailinfo == null) {
                detailinfo = new ArrayList<Dj.Detailinfos.Detailinfo>();
            }
            return this.detailinfo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="submit_addjs" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="submit_modjs" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="dcol" maxOccurs="200">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute ref="{}name use="required""/>
         *                 &lt;attribute ref="{}cname use="required""/>
         *                 &lt;attribute ref="{}type"/>
         *                 &lt;attribute ref="{}singleline"/>
         *                 &lt;attribute ref="{}size"/>
         *                 &lt;attribute ref="{}required"/>
         *                 &lt;attribute ref="{}format"/>
         *                 &lt;attribute ref="{}default"/>
         *                 &lt;attribute ref="{}readonly"/>
         *                 &lt;attribute ref="{}modify"/>
         *                 &lt;attribute ref="{}dqname"/>
         *                 &lt;attribute ref="{}retval"/>
         *                 &lt;attribute ref="{}xycol"/>
         *                 &lt;attribute ref="{}value"/>
         *                 &lt;attribute ref="{}other"/>
         *                 &lt;attribute ref="{}align"/>
         *                 &lt;attribute ref="{}onblur"/>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="dfoot" maxOccurs="10">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute ref="{}name use="required""/>
         *                 &lt;attribute ref="{}cname use="required""/>
         *                 &lt;attribute ref="{}type"/>
         *                 &lt;attribute ref="{}singleline"/>
         *                 &lt;attribute ref="{}size"/>
         *                 &lt;attribute ref="{}required"/>
         *                 &lt;attribute ref="{}format"/>
         *                 &lt;attribute ref="{}default"/>
         *                 &lt;attribute ref="{}readonly"/>
         *                 &lt;attribute ref="{}modify"/>
         *                 &lt;attribute ref="{}dqname"/>
         *                 &lt;attribute ref="{}retval"/>
         *                 &lt;attribute ref="{}xycol"/>
         *                 &lt;attribute ref="{}value"/>
         *                 &lt;attribute ref="{}other"/>
         *                 &lt;attribute ref="{}align"/>
         *                 &lt;attribute ref="{}onblur"/>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute ref="{}name use="required""/>
         *       &lt;attribute ref="{}cname use="required""/>
         *       &lt;attribute ref="{}tablename use="required""/>
         *       &lt;attribute ref="{}pagesize use="required""/>
         *       &lt;attribute ref="{}colname use="required""/>
         *       &lt;attribute ref="{}mxcc"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "submitAddjs",
            "submitModjs",
            "dcol",
            "dfoot"
        })
        public static class Detailinfo {

            @XmlElement(name = "submit_addjs", required = true)
            protected String submitAddjs;
            @XmlElement(name = "submit_modjs", required = true)
            protected String submitModjs;
            @XmlElement(required = true)
            protected List<Dj.Detailinfos.Detailinfo.Dcol> dcol;
            @XmlElement(required = true)
            protected List<Dj.Detailinfos.Detailinfo.Dfoot> dfoot;
            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "cname", required = true)
            protected String cname;
            @XmlAttribute(name = "tablename", required = true)
            protected String tablename;
            @XmlAttribute(name = "pagesize", required = true)
            protected BigInteger pagesize;
            @XmlAttribute(name = "colname", required = true)
            protected String colname;
            @XmlAttribute(name = "mxcc")
            protected String mxcc;

            /**
             * Gets the value of the submitAddjs property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubmitAddjs() {
                return submitAddjs;
            }

            /**
             * Sets the value of the submitAddjs property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubmitAddjs(String value) {
                this.submitAddjs = value;
            }

            /**
             * Gets the value of the submitModjs property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubmitModjs() {
                return submitModjs;
            }

            /**
             * Sets the value of the submitModjs property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubmitModjs(String value) {
                this.submitModjs = value;
            }

            /**
             * Gets the value of the dcol property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dcol property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDcol().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Dj.Detailinfos.Detailinfo.Dcol }
             * 
             * 
             */
            public List<Dj.Detailinfos.Detailinfo.Dcol> getDcol() {
                if (dcol == null) {
                    dcol = new ArrayList<Dj.Detailinfos.Detailinfo.Dcol>();
                }
                return this.dcol;
            }

            /**
             * Gets the value of the dfoot property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dfoot property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDfoot().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Dj.Detailinfos.Detailinfo.Dfoot }
             * 
             * 
             */
            public List<Dj.Detailinfos.Detailinfo.Dfoot> getDfoot() {
                if (dfoot == null) {
                    dfoot = new ArrayList<Dj.Detailinfos.Detailinfo.Dfoot>();
                }
                return this.dfoot;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the cname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCname() {
                return cname;
            }

            /**
             * Sets the value of the cname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCname(String value) {
                this.cname = value;
            }

            /**
             * Gets the value of the tablename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTablename() {
                return tablename;
            }

            /**
             * Sets the value of the tablename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTablename(String value) {
                this.tablename = value;
            }

            /**
             * Gets the value of the pagesize property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPagesize() {
                return pagesize;
            }

            /**
             * Sets the value of the pagesize property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPagesize(BigInteger value) {
                this.pagesize = value;
            }

            /**
             * Gets the value of the colname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColname() {
                return colname;
            }

            /**
             * Sets the value of the colname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColname(String value) {
                this.colname = value;
            }

            /**
             * Gets the value of the mxcc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMxcc() {
                return mxcc;
            }

            /**
             * Sets the value of the mxcc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMxcc(String value) {
                this.mxcc = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute ref="{}name use="required""/>
             *       &lt;attribute ref="{}cname use="required""/>
             *       &lt;attribute ref="{}type"/>
             *       &lt;attribute ref="{}singleline"/>
             *       &lt;attribute ref="{}size"/>
             *       &lt;attribute ref="{}required"/>
             *       &lt;attribute ref="{}format"/>
             *       &lt;attribute ref="{}default"/>
             *       &lt;attribute ref="{}readonly"/>
             *       &lt;attribute ref="{}modify"/>
             *       &lt;attribute ref="{}dqname"/>
             *       &lt;attribute ref="{}retval"/>
             *       &lt;attribute ref="{}xycol"/>
             *       &lt;attribute ref="{}value"/>
             *       &lt;attribute ref="{}other"/>
             *       &lt;attribute ref="{}align"/>
             *       &lt;attribute ref="{}onblur"/>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Dcol {

                @XmlAttribute(name = "name", required = true)
                protected String name;
                @XmlAttribute(name = "cname", required = true)
                protected String cname;
                @XmlAttribute(name = "type")
                protected String type;
                @XmlAttribute(name = "singleline")
                protected String singleline;
                @XmlAttribute(name = "size")
                protected BigInteger size;
                @XmlAttribute(name = "required")
                protected Boolean required;
                @XmlAttribute(name = "format")
                protected String format;
                @XmlAttribute(name = "default")
                protected String _default;
                @XmlAttribute(name = "readonly")
                protected Boolean readonly;
                @XmlAttribute(name = "modify")
                protected Boolean modify;
                @XmlAttribute(name = "dqname")
                protected String dqname;
                @XmlAttribute(name = "retval")
                protected String retval;
                @XmlAttribute(name = "xycol")
                protected String xycol;
                @XmlAttribute(name = "value")
                protected String value;
                @XmlAttribute(name = "other")
                protected String other;
                @XmlAttribute(name = "align")
                protected String align;
                @XmlAttribute(name = "onblur")
                protected String onblur;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the cname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCname() {
                    return cname;
                }

                /**
                 * Sets the value of the cname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCname(String value) {
                    this.cname = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the singleline property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSingleline() {
                    return singleline;
                }

                /**
                 * Sets the value of the singleline property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSingleline(String value) {
                    this.singleline = value;
                }

                /**
                 * Gets the value of the size property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getSize() {
                    return size;
                }

                /**
                 * Sets the value of the size property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setSize(BigInteger value) {
                    this.size = value;
                }

                /**
                 * Gets the value of the required property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isRequired() {
                    return required;
                }

                /**
                 * Sets the value of the required property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setRequired(Boolean value) {
                    this.required = value;
                }

                /**
                 * Gets the value of the format property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFormat() {
                    return format;
                }

                /**
                 * Sets the value of the format property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFormat(String value) {
                    this.format = value;
                }

                /**
                 * Gets the value of the default property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDefault() {
                    return _default;
                }

                /**
                 * Sets the value of the default property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDefault(String value) {
                    this._default = value;
                }

                /**
                 * Gets the value of the readonly property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isReadonly() {
                    return readonly;
                }

                /**
                 * Sets the value of the readonly property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setReadonly(Boolean value) {
                    this.readonly = value;
                }

                /**
                 * Gets the value of the modify property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isModify() {
                    return modify;
                }

                /**
                 * Sets the value of the modify property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setModify(Boolean value) {
                    this.modify = value;
                }

                /**
                 * Gets the value of the dqname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDqname() {
                    return dqname;
                }

                /**
                 * Sets the value of the dqname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDqname(String value) {
                    this.dqname = value;
                }

                /**
                 * Gets the value of the retval property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRetval() {
                    return retval;
                }

                /**
                 * Sets the value of the retval property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRetval(String value) {
                    this.retval = value;
                }

                /**
                 * Gets the value of the xycol property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getXycol() {
                    return xycol;
                }

                /**
                 * Sets the value of the xycol property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setXycol(String value) {
                    this.xycol = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the other property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOther() {
                    return other;
                }

                /**
                 * Sets the value of the other property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOther(String value) {
                    this.other = value;
                }

                /**
                 * Gets the value of the align property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAlign() {
                    return align;
                }

                /**
                 * Sets the value of the align property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAlign(String value) {
                    this.align = value;
                }

                /**
                 * Gets the value of the onblur property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOnblur() {
                    return onblur;
                }

                /**
                 * Sets the value of the onblur property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOnblur(String value) {
                    this.onblur = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute ref="{}name use="required""/>
             *       &lt;attribute ref="{}cname use="required""/>
             *       &lt;attribute ref="{}type"/>
             *       &lt;attribute ref="{}singleline"/>
             *       &lt;attribute ref="{}size"/>
             *       &lt;attribute ref="{}required"/>
             *       &lt;attribute ref="{}format"/>
             *       &lt;attribute ref="{}default"/>
             *       &lt;attribute ref="{}readonly"/>
             *       &lt;attribute ref="{}modify"/>
             *       &lt;attribute ref="{}dqname"/>
             *       &lt;attribute ref="{}retval"/>
             *       &lt;attribute ref="{}xycol"/>
             *       &lt;attribute ref="{}value"/>
             *       &lt;attribute ref="{}other"/>
             *       &lt;attribute ref="{}align"/>
             *       &lt;attribute ref="{}onblur"/>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Dfoot {

                @XmlAttribute(name = "name", required = true)
                protected String name;
                @XmlAttribute(name = "cname", required = true)
                protected String cname;
                @XmlAttribute(name = "type")
                protected String type;
                @XmlAttribute(name = "singleline")
                protected String singleline;
                @XmlAttribute(name = "size")
                protected BigInteger size;
                @XmlAttribute(name = "required")
                protected Boolean required;
                @XmlAttribute(name = "format")
                protected String format;
                @XmlAttribute(name = "default")
                protected String _default;
                @XmlAttribute(name = "readonly")
                protected Boolean readonly;
                @XmlAttribute(name = "modify")
                protected Boolean modify;
                @XmlAttribute(name = "dqname")
                protected String dqname;
                @XmlAttribute(name = "retval")
                protected String retval;
                @XmlAttribute(name = "xycol")
                protected String xycol;
                @XmlAttribute(name = "value")
                protected String value;
                @XmlAttribute(name = "other")
                protected String other;
                @XmlAttribute(name = "align")
                protected String align;
                @XmlAttribute(name = "onblur")
                protected String onblur;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the cname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCname() {
                    return cname;
                }

                /**
                 * Sets the value of the cname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCname(String value) {
                    this.cname = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the singleline property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSingleline() {
                    return singleline;
                }

                /**
                 * Sets the value of the singleline property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSingleline(String value) {
                    this.singleline = value;
                }

                /**
                 * Gets the value of the size property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getSize() {
                    return size;
                }

                /**
                 * Sets the value of the size property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setSize(BigInteger value) {
                    this.size = value;
                }

                /**
                 * Gets the value of the required property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isRequired() {
                    return required;
                }

                /**
                 * Sets the value of the required property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setRequired(Boolean value) {
                    this.required = value;
                }

                /**
                 * Gets the value of the format property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFormat() {
                    return format;
                }

                /**
                 * Sets the value of the format property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFormat(String value) {
                    this.format = value;
                }

                /**
                 * Gets the value of the default property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDefault() {
                    return _default;
                }

                /**
                 * Sets the value of the default property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDefault(String value) {
                    this._default = value;
                }

                /**
                 * Gets the value of the readonly property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isReadonly() {
                    return readonly;
                }

                /**
                 * Sets the value of the readonly property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setReadonly(Boolean value) {
                    this.readonly = value;
                }

                /**
                 * Gets the value of the modify property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isModify() {
                    return modify;
                }

                /**
                 * Sets the value of the modify property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setModify(Boolean value) {
                    this.modify = value;
                }

                /**
                 * Gets the value of the dqname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDqname() {
                    return dqname;
                }

                /**
                 * Sets the value of the dqname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDqname(String value) {
                    this.dqname = value;
                }

                /**
                 * Gets the value of the retval property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRetval() {
                    return retval;
                }

                /**
                 * Sets the value of the retval property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRetval(String value) {
                    this.retval = value;
                }

                /**
                 * Gets the value of the xycol property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getXycol() {
                    return xycol;
                }

                /**
                 * Sets the value of the xycol property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setXycol(String value) {
                    this.xycol = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the other property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOther() {
                    return other;
                }

                /**
                 * Sets the value of the other property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOther(String value) {
                    this.other = value;
                }

                /**
                 * Gets the value of the align property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAlign() {
                    return align;
                }

                /**
                 * Sets the value of the align property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAlign(String value) {
                    this.align = value;
                }

                /**
                 * Gets the value of the onblur property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOnblur() {
                    return onblur;
                }

                /**
                 * Sets the value of the onblur property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOnblur(String value) {
                    this.onblur = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="mcol" maxOccurs="200">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute ref="{}name use="required""/>
     *                 &lt;attribute ref="{}cname use="required""/>
     *                 &lt;attribute ref="{}type"/>
     *                 &lt;attribute ref="{}singleline"/>
     *                 &lt;attribute ref="{}size"/>
     *                 &lt;attribute ref="{}required"/>
     *                 &lt;attribute ref="{}format"/>
     *                 &lt;attribute ref="{}default"/>
     *                 &lt;attribute ref="{}readonly"/>
     *                 &lt;attribute ref="{}modify"/>
     *                 &lt;attribute ref="{}dqname"/>
     *                 &lt;attribute ref="{}retval"/>
     *                 &lt;attribute ref="{}xycol"/>
     *                 &lt;attribute ref="{}value"/>
     *                 &lt;attribute ref="{}other"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute ref="{}tablename use="required""/>
     *       &lt;attribute ref="{}bchz"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mcol"
    })
    public static class Masterinfo {

        @XmlElement(required = true)
        protected List<Dj.Masterinfo.Mcol> mcol;
        @XmlAttribute(name = "tablename", required = true)
        protected String tablename;
        @XmlAttribute(name = "bchz")
        protected Boolean bchz;

        /**
         * Gets the value of the mcol property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mcol property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMcol().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dj.Masterinfo.Mcol }
         * 
         * 
         */
        public List<Dj.Masterinfo.Mcol> getMcol() {
            if (mcol == null) {
                mcol = new ArrayList<Dj.Masterinfo.Mcol>();
            }
            return this.mcol;
        }

        /**
         * Gets the value of the tablename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTablename() {
            return tablename;
        }

        /**
         * Sets the value of the tablename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTablename(String value) {
            this.tablename = value;
        }

        /**
         * Gets the value of the bchz property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isBchz() {
            return bchz;
        }

        /**
         * Sets the value of the bchz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setBchz(Boolean value) {
            this.bchz = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute ref="{}name use="required""/>
         *       &lt;attribute ref="{}cname use="required""/>
         *       &lt;attribute ref="{}type"/>
         *       &lt;attribute ref="{}singleline"/>
         *       &lt;attribute ref="{}size"/>
         *       &lt;attribute ref="{}required"/>
         *       &lt;attribute ref="{}format"/>
         *       &lt;attribute ref="{}default"/>
         *       &lt;attribute ref="{}readonly"/>
         *       &lt;attribute ref="{}modify"/>
         *       &lt;attribute ref="{}dqname"/>
         *       &lt;attribute ref="{}retval"/>
         *       &lt;attribute ref="{}xycol"/>
         *       &lt;attribute ref="{}value"/>
         *       &lt;attribute ref="{}other"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Mcol {

            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "cname", required = true)
            protected String cname;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "singleline")
            protected String singleline;
            @XmlAttribute(name = "size")
            protected BigInteger size;
            @XmlAttribute(name = "required")
            protected Boolean required;
            @XmlAttribute(name = "format")
            protected String format;
            @XmlAttribute(name = "default")
            protected String _default;
            @XmlAttribute(name = "readonly")
            protected Boolean readonly;
            @XmlAttribute(name = "modify")
            protected Boolean modify;
            @XmlAttribute(name = "dqname")
            protected String dqname;
            @XmlAttribute(name = "retval")
            protected String retval;
            @XmlAttribute(name = "xycol")
            protected String xycol;
            @XmlAttribute(name = "value")
            protected String value;
            @XmlAttribute(name = "other")
            protected String other;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the cname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCname() {
                return cname;
            }

            /**
             * Sets the value of the cname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCname(String value) {
                this.cname = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the singleline property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSingleline() {
                return singleline;
            }

            /**
             * Sets the value of the singleline property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSingleline(String value) {
                this.singleline = value;
            }

            /**
             * Gets the value of the size property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getSize() {
                return size;
            }

            /**
             * Sets the value of the size property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setSize(BigInteger value) {
                this.size = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setRequired(Boolean value) {
                this.required = value;
            }

            /**
             * Gets the value of the format property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFormat() {
                return format;
            }

            /**
             * Sets the value of the format property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFormat(String value) {
                this.format = value;
            }

            /**
             * Gets the value of the default property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDefault() {
                return _default;
            }

            /**
             * Sets the value of the default property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDefault(String value) {
                this._default = value;
            }

            /**
             * Gets the value of the readonly property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isReadonly() {
                return readonly;
            }

            /**
             * Sets the value of the readonly property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setReadonly(Boolean value) {
                this.readonly = value;
            }

            /**
             * Gets the value of the modify property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isModify() {
                return modify;
            }

            /**
             * Sets the value of the modify property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setModify(Boolean value) {
                this.modify = value;
            }

            /**
             * Gets the value of the dqname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDqname() {
                return dqname;
            }

            /**
             * Sets the value of the dqname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDqname(String value) {
                this.dqname = value;
            }

            /**
             * Gets the value of the retval property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRetval() {
                return retval;
            }

            /**
             * Sets the value of the retval property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRetval(String value) {
                this.retval = value;
            }

            /**
             * Gets the value of the xycol property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXycol() {
                return xycol;
            }

            /**
             * Sets the value of the xycol property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXycol(String value) {
                this.xycol = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the other property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOther() {
                return other;
            }

            /**
             * Sets the value of the other property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOther(String value) {
                this.other = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="operation" maxOccurs="100">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute ref="{}name use="required""/>
     *                 &lt;attribute ref="{}cname use="required""/>
     *                 &lt;attribute ref="{}key"/>
     *                 &lt;attribute ref="{}disable"/>
     *                 &lt;attribute ref="{}type"/>
     *                 &lt;attribute ref="{}ac"/>
     *                 &lt;attribute ref="{}djxg"/>
     *                 &lt;attribute ref="{}retval"/>
     *                 &lt;attribute ref="{}djlock"/>
     *                 &lt;attribute ref="{}other"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operation"
    })
    public static class Operations {

        @XmlElement(required = true)
        protected List<Dj.Operations.Operation> operation;

        /**
         * Gets the value of the operation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the operation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOperation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dj.Operations.Operation }
         * 
         * 
         */
        public List<Dj.Operations.Operation> getOperation() {
            if (operation == null) {
                operation = new ArrayList<Dj.Operations.Operation>();
            }
            return this.operation;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute ref="{}name use="required""/>
         *       &lt;attribute ref="{}cname use="required""/>
         *       &lt;attribute ref="{}key"/>
         *       &lt;attribute ref="{}disable"/>
         *       &lt;attribute ref="{}type"/>
         *       &lt;attribute ref="{}ac"/>
         *       &lt;attribute ref="{}djxg"/>
         *       &lt;attribute ref="{}retval"/>
         *       &lt;attribute ref="{}djlock"/>
         *       &lt;attribute ref="{}other"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Operation {

            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "cname", required = true)
            protected String cname;
            @XmlAttribute(name = "key")
            protected String key;
            @XmlAttribute(name = "disable")
            protected Boolean disable;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "ac")
            protected String ac;
            @XmlAttribute(name = "djxg")
            protected String djxg;
            @XmlAttribute(name = "retval")
            protected String retval;
            @XmlAttribute(name = "djlock")
            protected String djlock;
            @XmlAttribute(name = "other")
            protected String other;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the cname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCname() {
                return cname;
            }

            /**
             * Sets the value of the cname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCname(String value) {
                this.cname = value;
            }

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the disable property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isDisable() {
                return disable;
            }

            /**
             * Sets the value of the disable property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setDisable(Boolean value) {
                this.disable = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the ac property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAc() {
                return ac;
            }

            /**
             * Sets the value of the ac property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAc(String value) {
                this.ac = value;
            }

            /**
             * Gets the value of the djxg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDjxg() {
                return djxg;
            }

            /**
             * Sets the value of the djxg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDjxg(String value) {
                this.djxg = value;
            }

            /**
             * Gets the value of the retval property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRetval() {
                return retval;
            }

            /**
             * Sets the value of the retval property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRetval(String value) {
                this.retval = value;
            }

            /**
             * Gets the value of the djlock property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDjlock() {
                return djlock;
            }

            /**
             * Sets the value of the djlock property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDjlock(String value) {
                this.djlock = value;
            }

            /**
             * Gets the value of the other property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOther() {
                return other;
            }

            /**
             * Sets the value of the other property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOther(String value) {
                this.other = value;
            }

        }

    }

}
